config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :abonos
  resources :item_lista
  resources :item_pedidos
  resources :pedidos
  resources :lista
  resources :categoria_proveedors
  resources :item_proveedors
  resources :items
  resources :restaurantes
  resources :categoria
  resources :proveedors
  devise_for :users
  root 'items#index'
  get 'user_info', to: 'items#user_info', :as => 'user_info' #PERFIL
  get 'new_user', to: 'items#new_user', :as => 'new_user'    #NUEVO USUARIO
  get 'all_users', to: 'items#all_users', :as => 'all_users' #TODOS LOS USUARIOS
  post 'create_new_user', to: 'items#create_new_user', :as => 'create_new_user'
  get 'change_password', to: 'items#change_password', :as => 'change_password' #CAMBIAR CONTRASENA
  post 'new_change_password', to: 'items#new_change_password', :as => 'new_change_password'
  post 'update_estado_actual', to: 'pedidos#update_estado_actual', :as => 'update_estado_actual'

end

app/models/abono.rb
class Abono < ActiveRecord::Base
  belongs_to :proveedor
  belongs_to :pedido
  belongs_to :user
end

app/models/categoria_proveedor.rb
class CategoriaProveedor < ActiveRecord::Base
  belongs_to :proveedor
  belongs_to :categorium
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
  belongs_to :proveedor
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :categorium
end

app/models/item_listum.rb
class ItemListum < ActiveRecord::Base
  belongs_to :item
  belongs_to :listum
end

app/models/item_pedido.rb
class ItemPedido < ActiveRecord::Base
  belongs_to :proveedor
  belongs_to :item
end

app/models/item_proveedor.rb
class ItemProveedor < ActiveRecord::Base
  belongs_to :item
  belongs_to :proveedor
end

app/models/listum.rb
class Listum < ActiveRecord::Base
  belongs_to :restaurante
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :restaurante
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
  belongs_to :user
end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
  belongs_to :user
end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :pedido
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/abonos_controller.rb
class AbonosController < ApplicationController
  before_action :set_abono, only: [:show, :edit, :update, :destroy]

  # GET /abonos
  # GET /abonos.json
  def index
    @abonos = Abono.all
  end

  # GET /abonos/1
  # GET /abonos/1.json
  def show
  end

  # GET /abonos/new
  def new
    @abono = Abono.new
  end

  # GET /abonos/1/edit
  def edit
  end

  # POST /abonos
  # POST /abonos.json
  def create
    @abono = Abono.new(abono_params)

    respond_to do |format|
      if @abono.save
        format.html { redirect_to @abono, notice: 'Abono was successfully created.' }
        format.json { render :show, status: :created, location: @abono }
      else
        format.html { render :new }
        format.json { render json: @abono.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abonos/1
  # PATCH/PUT /abonos/1.json
  def update
    respond_to do |format|
      if @abono.update(abono_params)
        format.html { redirect_to @abono, notice: 'Abono was successfully updated.' }
        format.json { render :show, status: :ok, location: @abono }
      else
        format.html { render :edit }
        format.json { render json: @abono.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abonos/1
  # DELETE /abonos/1.json
  def destroy
    @abono.destroy
    respond_to do |format|
      format.html { redirect_to abonos_url, notice: 'Abono was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abono
      @abono = Abono.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def abono_params
      params.require(:abono).permit(:proveedor_id, :pedido_id, :monto, :comentario, :user_id)
    end
end

app/helpers/abonos_helper.rb
module AbonosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/item_lista_helper.rb
module ItemListaHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lista_helper.rb
module ListaHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/abonos/_form.html.erb
<%= form_for(@abono) do |f| %>
  <% if @abono.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@abono.errors.count, "error") %> prohibited this abono from being saved:</h2>

      <ul>
      <% @abono.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :proveedor_id %><br>
    <%= f.text_field :proveedor_id %>
  </div>
  <div class="field">
    <%= f.label :pedido_id %><br>
    <%= f.text_field :pedido_id %>
  </div>
  <div class="field">
    <%= f.label :monto %><br>
    <%= f.text_field :monto %>
  </div>
  <div class="field">
    <%= f.label :comentario %><br>
    <%= f.text_area :comentario %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/abonos/edit.html.erb
<h1>Editing Abono</h1>

<%= render 'form' %>

<%= link_to 'Show', @abono %> |
<%= link_to 'Back', abonos_path %>

app/views/abonos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Abonos</h1>

<table>
  <thead>
    <tr>
      <th>Proveedor</th>
      <th>Pedido</th>
      <th>Monto</th>
      <th>Comentario</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @abonos.each do |abono| %>
      <tr>
        <td><%= abono.proveedor %></td>
        <td><%= abono.pedido %></td>
        <td><%= abono.monto %></td>
        <td><%= abono.comentario %></td>
        <td><%= abono.user %></td>
        <td><%= link_to 'Show', abono %></td>
        <td><%= link_to 'Edit', edit_abono_path(abono) %></td>
        <td><%= link_to 'Destroy', abono, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Abono', new_abono_path %>

app/views/abonos/new.html.erb
<h1>New Abono</h1>

<%= render 'form' %>

<%= link_to 'Back', abonos_path %>

app/views/abonos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Proveedor:</strong>
  <%= @abono.proveedor %>
</p>

<p>
  <strong>Pedido:</strong>
  <%= @abono.pedido %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @abono.monto %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @abono.comentario %>
</p>

<p>
  <strong>User:</strong>
  <%= @abono.user %>
</p>

<%= link_to 'Edit', edit_abono_path(@abono) %> |
<%= link_to 'Back', abonos_path %>