config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :abonos
  resources :item_lista
  resources :item_pedidos
  resources :pedidos
  resources :lista
  resources :categoria_proveedors
  resources :item_proveedors
  resources :items
  resources :restaurantes
  resources :categoria
  resources :proveedors
  devise_for :users
  root 'items#index'
  get 'user_info', to: 'items#user_info', :as => 'user_info' #PERFIL
  get 'new_user', to: 'items#new_user', :as => 'new_user'    #NUEVO USUARIO
  get 'all_users', to: 'items#all_users', :as => 'all_users' #TODOS LOS USUARIOS
  post 'create_new_user', to: 'items#create_new_user', :as => 'create_new_user'
  get 'change_password', to: 'items#change_password', :as => 'change_password' #CAMBIAR CONTRASENA
  post 'new_change_password', to: 'items#new_change_password', :as => 'new_change_password'
  post 'update_estado_actual', to: 'pedidos#update_estado_actual', :as => 'update_estado_actual'

end

app/models/abono.rb
class Abono < ActiveRecord::Base
  belongs_to :proveedor
  belongs_to :pedido
  belongs_to :user
end

app/models/categoria_proveedor.rb
class CategoriaProveedor < ActiveRecord::Base
  belongs_to :proveedor
  belongs_to :categorium
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
  belongs_to :proveedor
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :categorium
end

app/models/item_listum.rb
class ItemListum < ActiveRecord::Base
  belongs_to :item
  belongs_to :listum
end

app/models/item_pedido.rb
class ItemPedido < ActiveRecord::Base
  belongs_to :proveedor
  belongs_to :item
end

app/models/item_proveedor.rb
class ItemProveedor < ActiveRecord::Base
  belongs_to :item
  belongs_to :proveedor
end

app/models/listum.rb
class Listum < ActiveRecord::Base
  belongs_to :restaurante
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :restaurante
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
  belongs_to :user
end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
  belongs_to :user
end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :pedido
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/categoria_proveedors_controller.rb
class CategoriaProveedorsController < ApplicationController
  before_action :set_categoria_proveedor, only: [:show, :edit, :update, :destroy]

  # GET /categoria_proveedors
  # GET /categoria_proveedors.json
  def index
    @categoria_proveedors = CategoriaProveedor.all
  end

  # GET /categoria_proveedors/1
  # GET /categoria_proveedors/1.json
  def show
  end

  # GET /categoria_proveedors/new
  def new
    @categoria_proveedor = CategoriaProveedor.new
    @proveedors = Proveedor.all
    @categoria = Categorium.all
  end

  # GET /categoria_proveedors/1/edit
  def edit
  end

  # POST /categoria_proveedors
  # POST /categoria_proveedors.json
  def create
    @categoria_proveedor = CategoriaProveedor.new(categoria_proveedor_params)

    respond_to do |format|
      if @categoria_proveedor.save
        format.html { redirect_to @categoria_proveedor, notice: 'Categoria proveedor was successfully created.' }
        format.json { render :show, status: :created, location: @categoria_proveedor }
      else
        format.html { render :new }
        format.json { render json: @categoria_proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria_proveedors/1
  # PATCH/PUT /categoria_proveedors/1.json
  def update
    respond_to do |format|
      if @categoria_proveedor.update(categoria_proveedor_params)
        format.html { redirect_to @categoria_proveedor, notice: 'Categoria proveedor was successfully updated.' }
        format.json { render :show, status: :ok, location: @categoria_proveedor }
      else
        format.html { render :edit }
        format.json { render json: @categoria_proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria_proveedors/1
  # DELETE /categoria_proveedors/1.json
  def destroy
    @categoria_proveedor.destroy
    respond_to do |format|
      format.html { redirect_to categoria_proveedors_url, notice: 'Categoria proveedor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria_proveedor
      @categoria_proveedor = CategoriaProveedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoria_proveedor_params
      params.require(:categoria_proveedor).permit(:proveedor_id, :categorium_id)
    end
end

app/helpers/abonos_helper.rb
module AbonosHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/categoria_proveedors_helper.rb
module CategoriaProveedorsHelper
end

app/helpers/item_lista_helper.rb
module ItemListaHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lista_helper.rb
module ListaHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/categoria_proveedors/_form.html.erb
<%= form_for(@categoria_proveedor) do |f| %>
  <% if @categoria_proveedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria_proveedor.errors.count, "error") %> prohibited this categoria_proveedor from being saved:</h2>

      <ul>
      <% @categoria_proveedor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :proveedor_id %><br>
    <%= f.select :proveedor_id, options_for_select(@proveedors.map{ |c| [c.nombre, c.id, {'data-id'=>c.id}] }) %>
  </div>
  <div class="field">
    <%= f.label :categorium_id %><br>
    <%= f.select :categorium_id, options_for_select(@categoria.map{ |c| [c.nombre, c.id, {'data-id'=>c.id}] }) %>
  </div>
  <div class="actions">
    <%= f.submit "Crear proveedor de categoría"%>
  </div>
<% end %>

app/views/categoria_proveedors/edit.html.erb
<h1>Editing Categoria Proveedor</h1>

<%= render 'form' %>

<%= link_to 'Show', @categoria_proveedor %> |
<%= link_to 'Back', categoria_proveedors_path %>

app/views/categoria_proveedors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proveedores por categorías</h1>

<table border="1">
  <thead>
    <tr>
      <th>Proveedor</th>
      <th>Categorium</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categoria_proveedors.each do |categoria_proveedor| %>
      <tr>
        <td><%= categoria_proveedor.proveedor.nombre %></td>
        <td><%= categoria_proveedor.categorium.nombre %></td>
        <!--<td><%= link_to 'Mostrar', categoria_proveedor %></td>-->
        <!--<td> <%= link_to 'Editar', edit_categoria_proveedor_path(categoria_proveedor) %> </td>-->
        <td><%= link_to 'Eliminar', categoria_proveedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.rol == ADMIN %>
    <button type="button"><%= link_to 'Nuevo proveedor de categoría', new_categoria_proveedor_path %></button>

<% end %>

app/views/categoria_proveedors/new.html.erb
<h1>Nuevo proveedor de categoría</h1>

<%= render 'form' %>

<%= link_to 'Volver', categoria_proveedors_path %>

app/views/categoria_proveedors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Proveedor:</strong>
  <%= @categoria_proveedor.proveedor.nombre %>
</p>

<p>
  <strong>Categorium:</strong>
  <%= @categoria_proveedor.categorium.nombre %>
</p>

<%= link_to 'Edit', edit_categoria_proveedor_path(@categoria_proveedor) %> |
<%= link_to 'Back', categoria_proveedors_path %>