config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :abonos
  resources :item_lista
  resources :item_pedidos
  resources :pedidos
  resources :lista
  resources :categoria_proveedors
  resources :item_proveedors
  resources :items
  resources :restaurantes
  resources :categoria
  resources :proveedors
  devise_for :users
  root 'items#index'
  get 'user_info', to: 'items#user_info', :as => 'user_info' #PERFIL
  get 'new_user', to: 'items#new_user', :as => 'new_user'    #NUEVO USUARIO
  get 'all_users', to: 'items#all_users', :as => 'all_users' #TODOS LOS USUARIOS
  post 'create_new_user', to: 'items#create_new_user', :as => 'create_new_user'
  get 'change_password', to: 'items#change_password', :as => 'change_password' #CAMBIAR CONTRASENA
  post 'new_change_password', to: 'items#new_change_password', :as => 'new_change_password'
  post 'update_estado_actual', to: 'pedidos#update_estado_actual', :as => 'update_estado_actual'

end

app/models/abono.rb
class Abono < ActiveRecord::Base
  belongs_to :proveedor
  belongs_to :pedido
  belongs_to :user
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
  belongs_to :proveedor
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :categorium
end

app/models/item_listum.rb
class ItemListum < ActiveRecord::Base
  belongs_to :item
  belongs_to :listum
end

app/models/item_pedido.rb
class ItemPedido < ActiveRecord::Base
  belongs_to :proveedor
  belongs_to :item
end

app/models/item_proveedor.rb
class ItemProveedor < ActiveRecord::Base
  belongs_to :item
  belongs_to :proveedor
end

app/models/listum.rb
class Listum < ActiveRecord::Base
  belongs_to :restaurante
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :restaurante
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
  belongs_to :user
end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
  belongs_to :user
end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :pedido
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/item_proveedors_controller.rb
class ItemProveedorsController < ApplicationController
  before_action :set_item_proveedor, only: [:show, :edit, :update, :destroy]

  # GET /item_proveedors
  # GET /item_proveedors.json
  def index
    if current_user.rol == ADMIN || current_user.rol == OPERARIO
      @item_proveedors = ItemProveedor.all
    elsif current_user.rol == PROVEEDOR
      @item_proveedors = ItemProveedor.where(:proveedor_id => Proveedor.find_by_user_id(current_user.id).id)
    else
      redirect_to '/items'
    end
  end

  # GET /item_proveedors/1
  # GET /item_proveedors/1.json
  def show
    if current_user.rol == ADMIN || current_user.rol == OPERARIO
    else
      redirect_to '/items'
    end
  end

  # GET /item_proveedors/new
  def new
    if current_user.rol == ADMIN
      @item_proveedor = ItemProveedor.new
      @items = Item.all
      @proveedors = Proveedor.all
    else
      redirect_to '/items'
    end

  end

  # GET /item_proveedors/1/edit
  def edit
    if current_user.rol == ADMIN
      @items = Item.all
      @proveedors = Proveedor.all
    else
      redirect_to '/items'
    end


  end

  # POST /item_proveedors
  # POST /item_proveedors.json
  def create
    @item_proveedor = ItemProveedor.new(item_proveedor_params)

    respond_to do |format|
      if @item_proveedor.save
        format.html { redirect_to @item_proveedor, notice: 'Item proveedor was successfully created.' }
        format.json { render :show, status: :created, location: @item_proveedor }
      else
        format.html { render :new }
        format.json { render json: @item_proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_proveedors/1
  # PATCH/PUT /item_proveedors/1.json
  def update
    respond_to do |format|
      if @item_proveedor.update(item_proveedor_params)
        format.html { redirect_to @item_proveedor, notice: 'Item proveedor was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_proveedor }
      else
        format.html { render :edit }
        format.json { render json: @item_proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_proveedors/1
  # DELETE /item_proveedors/1.json
  def destroy
    @item_proveedor.destroy
    respond_to do |format|
      format.html { redirect_to item_proveedors_url, notice: 'Item proveedor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_proveedor
      @item_proveedor = ItemProveedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_proveedor_params
      params.require(:item_proveedor).permit(:item_id, :proveedor_id, :precio)
    end
end

app/helpers/abonos_helper.rb
module AbonosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/item_lista_helper.rb
module ItemListaHelper
end

app/helpers/item_proveedors_helper.rb
module ItemProveedorsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lista_helper.rb
module ListaHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/item_proveedors/_form.html.erb
<%= form_for(@item_proveedor) do |f| %>
  <% if @item_proveedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_proveedor.errors.count, "error") %> prohibited this item_proveedor from being saved:</h2>

      <ul>
      <% @item_proveedor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong><%= f.label :item_id %></strong><br>
    <%= f.select :item_id, options_for_select(@items.map{ |c| [c.nombre, c.id, {'data-id'=>c.id}] },(@item_proveedor.item_id)) %>
  </div>
  <div class="field">
    <strong><%= f.label :proveedor_id %></strong><br>
    <%= f.select :proveedor_id, options_for_select(@proveedors.map{ |c| [c.nombre, c.id, {'data-id'=>c.id}] },(@item_proveedor.proveedor_id)) %>
  </div>
  <div class="field">
    <strong><%= f.label :precio %></strong><br>
    <%= f.text_field :precio %>
  </div>
  <div class="actions">
    <%= f.submit "Crear proveedor de items"%>
  </div>
<% end %>

app/views/item_proveedors/edit.html.erb
<h1>Editar Proveedor de Items</h1>

<%= render 'form' %>

<!-- <%= link_to 'Ver', @item_proveedor %> | -->
<%= link_to 'Volver', item_proveedors_path %>

app/views/item_proveedors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proveedores de items</h1>

<table border="1">
  <thead>
    <tr>
      <th>Item</th>
      <th>Proveedor</th>
      <th>Precio</th>
      <% if current_user.rol == ADMIN || current_user.rol == OPERARIO %><th>Celular proveedor</th> <% end %>
      <% if current_user.rol == ADMIN %> <th colspan="3"></th> <% end %>
    </tr>
  </thead>

  <tbody>
    <% @item_proveedors.each do |item_proveedor| %>
      <tr>
        <td><%= item_proveedor.item.nombre %></td>
        <td><%= item_proveedor.proveedor.nombre %></td>
        <td><%= item_proveedor.precio %></td>
        <% if current_user.rol == ADMIN || current_user.rol == OPERARIO %><td><% item_proveedor.proveedor.user.celular%></td><% end %>
        <% if current_user.rol == ADMIN %> <td><!-- <%= link_to 'Ver', item_proveedor %> --></td>

        <td><%= link_to 'Editar', edit_item_proveedor_path(item_proveedor) %></td>
        <td><%= link_to 'Eliminar', item_proveedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.rol == ADMIN %>

<button type="button"><%= link_to 'Nuevo Proveedor de Item', new_item_proveedor_path %></button>

<% end %>

app/views/item_proveedors/new.html.erb
<h1>Nuevo Proveedor de Items</h1>

<%= render 'form' %>

<%= link_to 'Volver', item_proveedors_path %>

app/views/item_proveedors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item_proveedor.item.nombre %>
</p>

<p>
  <strong>Proveedor:</strong>
  <%= @item_proveedor.proveedor.user.email %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @item_proveedor.precio %>
</p>

<% if current_user.rol == ADMIN %>
<%= link_to 'Editar', edit_item_proveedor_path(@item_proveedor) %> |
    <% end %>
<%= link_to 'Volver', item_proveedors_path %>