config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :abonos
  resources :item_lista
  resources :item_pedidos
  resources :pedidos
  resources :lista
  resources :categoria_proveedors
  resources :item_proveedors
  resources :items
  resources :restaurantes
  resources :categoria
  resources :proveedors
  devise_for :users
  root 'items#index'
  get 'user_info', to: 'items#user_info', :as => 'user_info' #PERFIL
  get 'new_user', to: 'items#new_user', :as => 'new_user'    #NUEVO USUARIO
  get 'all_users', to: 'items#all_users', :as => 'all_users' #TODOS LOS USUARIOS
  post 'create_new_user', to: 'items#create_new_user', :as => 'create_new_user'
  get 'change_password', to: 'items#change_password', :as => 'change_password' #CAMBIAR CONTRASENA
  post 'new_change_password', to: 'items#new_change_password', :as => 'new_change_password'
  post 'update_estado_actual', to: 'pedidos#update_estado_actual', :as => 'update_estado_actual'

end

app/models/abono.rb
class Abono < ActiveRecord::Base
  belongs_to :proveedor
  belongs_to :pedido
  belongs_to :user
end

app/models/categoria_proveedor.rb
class CategoriaProveedor < ActiveRecord::Base
  belongs_to :proveedor
  belongs_to :categorium
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
  belongs_to :proveedor
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :categorium
end

app/models/item_listum.rb
class ItemListum < ActiveRecord::Base
  belongs_to :item
  belongs_to :listum
end

app/models/item_pedido.rb
class ItemPedido < ActiveRecord::Base
  belongs_to :proveedor
  belongs_to :item
end

app/models/item_proveedor.rb
class ItemProveedor < ActiveRecord::Base
  belongs_to :item
  belongs_to :proveedor
end

app/models/listum.rb
class Listum < ActiveRecord::Base
  belongs_to :restaurante
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :restaurante
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
  belongs_to :user
end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
  belongs_to :user
end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :pedido
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.all
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = Transfer.new(transfer_params)

    respond_to do |format|
      if @transfer.save
        format.html { redirect_to @transfer, notice: 'Transfer was successfully created.' }
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html { render :new }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:memo, :pedido_id, :from_id, :to_id)
    end
end

app/helpers/abonos_helper.rb
module AbonosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/item_lista_helper.rb
module ItemListaHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lista_helper.rb
module ListaHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_form.html.erb
<%= form_for(@transfer) do |f| %>
  <% if @transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% @transfer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_area :memo %>
  </div>
  <div class="field">
    <%= f.label :pedido_id %><br>
    <%= f.text_field :pedido_id %>
  </div>
  <div class="field">
    <%= f.label :from_id %><br>
    <%= f.number_field :from_id %>
  </div>
  <div class="field">
    <%= f.label :to_id %><br>
    <%= f.number_field :to_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transfers/edit.html.erb
<h1>Editing Transfer</h1>

<%= render 'form' %>

<%= link_to 'Show', @transfer %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transfers</h1>

<table>
  <thead>
    <tr>
      <th>Memo</th>
      <th>Pedido</th>
      <th>From</th>
      <th>To</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= transfer.memo %></td>
        <td><%= transfer.pedido %></td>
        <td><%= transfer.from_id %></td>
        <td><%= transfer.to_id %></td>
        <td><%= link_to 'Show', transfer %></td>
        <td><%= link_to 'Edit', edit_transfer_path(transfer) %></td>
        <td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transfer', new_transfer_path %>

app/views/transfers/new.html.erb
<h1>New Transfer</h1>

<%= render 'form' %>

<%= link_to 'Back', transfers_path %>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Memo:</strong>
  <%= @transfer.memo %>
</p>

<p>
  <strong>Pedido:</strong>
  <%= @transfer.pedido %>
</p>

<p>
  <strong>From:</strong>
  <%= @transfer.from_id %>
</p>

<p>
  <strong>To:</strong>
  <%= @transfer.to_id %>
</p>

<%= link_to 'Edit', edit_transfer_path(@transfer) %> |
<%= link_to 'Back', transfers_path %>